var sname = document.getElementById("name");
var desig = document.getElementById("desig");
var phone = document.getElementById("phone");
var email = document.getElementById("email");
var address = document.getElementById("address");
var depart = document.getElementById("depart");
var uni = document.getElementById("uni");
var year = document.getElementById("year");
var expertise1 = document.getElementById("expertise1");
var expertise2 = document.getElementById("expertise2");
var expertise3 = document.getElementById("expertise3");
var expertise4 = document.getElementById("expertise4");
var expertise5 = document.getElementById("expertise5");
var lang1 = document.getElementById("lang1");
var lang2 = document.getElementById("lang2");
var syear = document.getElementById("syear");
var eyear = document.getElementById("eyear");
var company = document.getElementById("company");
var companyadd = document.getElementById("companyadd");
var jobtitle = document.getElementById("jobtitle");
var achievements1 = document.getElementById("achievements1");
var achievements2 = document.getElementById("achievements2");
var submitbtn = document.getElementById("sub-btn");
var form = document.getElementById("form");
form === null || form === void 0 ? void 0 : form.addEventListener("submit", function (e) {
    e.preventDefault();
    localStorage.setItem("name", sname.value);
    localStorage.setItem("desig", desig.value);
    localStorage.setItem("phone", phone.value);
    localStorage.setItem("email", email.value);
    localStorage.setItem("address", address.value);
    localStorage.setItem("depart", depart.value);
    localStorage.setItem("uni ", uni.value);
    localStorage.setItem("year", year.value);
    localStorage.setItem("expertise1", expertise1.value);
    localStorage.setItem("expertise2", expertise2.value);
    localStorage.setItem("expertise3", expertise3.value);
    localStorage.setItem("expertise4", expertise4.value);
    localStorage.setItem("expertise5", expertise5.value);
    localStorage.setItem(" lang1", lang1.value);
    localStorage.setItem("lang2", lang2.value);
    localStorage.setItem("syear", syear.value);
    localStorage.setItem("eyear", eyear.value);
    localStorage.setItem("company", company.value);
    localStorage.setItem(" jobtitle ", jobtitle.value);
    localStorage.setItem("achievements1 ", achievements1.value);
    localStorage.setItem("achievements", achievements2.value);
    window.location.href = "./static/staticresume.html";
});
